name: release

on:
  push:
    branches:
      - main
    # Sequence of patterns matched against refs/tags
    tags:
      - 0.*

env:
  POETRY_VERSION: "1.4.0"

jobs:
  if_release:
    if: |
        true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==$POETRY_VERSION
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Build project for distribution
        run: poetry build --format sdist
      - name: Check Version
        id: check-version
        run: |
          echo version=$(poetry version --short) >> $GITHUB_OUTPUT
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --skip-existing
